bucket         = "my-opentofu-remote-state-bucket"
key            = "modules/synthefy-api-private/terraform.tfstate"
region         = "us-east-2"
dynamodb_table = "my-opentofu-state-locks"
encrypt        = true



